### ISSUE TITLE
Incompatible nokogiri for linux?

### ISSUE THREAD

**Issue by becky000** [becky000/sharks_ahead#4]
Installing gem in Linux Mint get error code upon running `sharks-ahead`:
```bash
rebecca@rebecca-virtual ~/code/sharks_ahead $ sharks-ahead
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': incompatible library version - /home/rebecca/.rvm/gems/ruby-2.3.1/gems/nokogiri-1.6.8/lib/nokogiri/nokogiri.so (LoadError)
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/rebecca/.rvm/gems/ruby-2.3.1/gems/nokogiri-1.6.8/lib/nokogiri.rb:32:in `rescue in <top (required)>'
        from /home/rebecca/.rvm/gems/ruby-2.3.1/gems/nokogiri-1.6.8/lib/nokogiri.rb:28:in `<top (required)>'
```
However, if installed locally in Linux and using command `bin/sharks-ahead`, runs as expected. Runs without error in Windows10 with gem installed, using `sharks-ahead`.

**Comment by becky000** [comment]
Incompatible with Bundler -v 1.13
